server:
  port: 8848
  connect-timeout: 10

mysql:
  uri: root:123456@tcp(127.0.0.1:3307)/test?charset=utf8mb4&collation=utf8mb4_general_ci&parseTime=True&loc=Local&timeout=10000ms
  table-prefix: tb
  show-sql: true

jwt:
  realm: test
  secret-key: unicorn
  expire: 2
  refresh: 2
  identity-key: jwt-identity

redis:
  uri: redis://127.0.0.1:6379
