definitions:
  request.CreateUser:
    properties:
      mobile:
        example: "18111111111"
        type: string
      name:
        example: 张三
        type: string
      password:
        type: string
      roleId:
        type: integer
    type: object
  resp.Response:
    properties:
      code:
        type: integer
      data: {}
      msg:
        type: string
      timestamp:
        type: integer
    type: object
info:
  contact:
    name: ppxb
    url: http://github.com/ppxb
  description: 一个使用Go开发的RBAC基础框架
  license:
    name: MIT
    url: https://github.com/ppxb/unicorn-go/blob/master/LICENCE
  termsOfService: http://swagger.io/terms/
  title: unicorn Framework
  version: 1.0.0
paths:
  /api/test/ping:
    get:
      consumes:
      - application/json
      description: Ping
      produces:
      - application/json
      responses:
        "20001":
          description: ok
          schema:
            $ref: '#/definitions/resp.Response'
      security:
      - Bearer: []
      tags:
      - 其他
  /api/v1/user/create:
    post:
      consumes:
      - application/json
      description: 创建用户
      parameters:
      - description: params
        in: body
        name: params
        required: true
        schema:
          $ref: '#/definitions/request.CreateUser'
      produces:
      - application/json
      responses:
        "20001":
          description: ok
          schema:
            $ref: '#/definitions/resp.Response'
      security:
      - Bearer: []
      tags:
      - 用户
securityDefinitions:
  Bearer:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
